dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh | bash
notification:
  slack:
    secure: gw6L/x3nsuJGkNuUjgLpU3WJWhe3eQgIzJb+dCrOtG614Eq13NQMqRPksR/4t0Gyf4bKIrtyzpY4+PrnLaG80pVB//oK6smSycfb99ZIAZUM5N8WroOdVGeCWKIn/5Q2XjAQkRQu5VkNubV7xC9ejEuBQgkwyjfgKRUd6RZtKq771LopwvK074S0otImSPUjYcaz+ETiQ9Uw88WeZQLzZTRJI37WgRIJQUbHUGz+MIE27yJGnPFub6fOU2sXYmYhrn47/Li5CWf3rVfijIyqwJcYAToETCgj4vh17r5aNCasRZZGQd8qaYbg4eWTfUUOn2zZ8s8VFGC5OnTH8enVQtIOkPV5ny5rS4MMXlRFvSx2YdSygzHAFFienQLJTXW2Yy4wSiqPL36tbGmE0eg8GeyZyFNb94vdH+hc3xU+qQ40aM8sKfHIz6EMvMjhhYwLpGM5uCQHdvggK/CQsur3LblvEU7EeVxqKT5/Jm6hKs+I/owHcvlINghhWw9umsi6Gmr9yyaulRKszwPHpeuiNW6YpvtYCP3VAsFZdAYACnmehlzAqma36regyj0QfOJ7R2R65AqC70P8aDyOmWjkeWci4c3y6k+Blgk3ribfJeyfcNQuq+K3b9FjLeQyCWnR0VxdI5crJ9zKYOb0DLsfiWFrGjaxY1J9BkeXpJzOwFw=
